language: java
os: linux
jdk: openjdk11
deploy:
  provider: lambda
  function_name: getCashFlows
  region: us-east-1
  role: arn:aws:iam::114344824111:role/service-role/wucashflowLambda
  runtime: java11
  module_name: "com.wuxwesty"
  handler_name: "GetCashFlowsHandler::handleRequest"
  memory_size: 512
  timeout: 30
  access_key_id:
  secret_access_key:
  zip: ./target/wucashflow-1.0.0.jar