language: java
jdk: openjdk11
deploy:
  provider: lambda
  function_name: getCashFlows
  region: us-east-1
  role: arn:aws:iam::114344824111:role/service-role/wucashflowLambda
  runtime: java11
  handler_name: com.wuxwesty.GetCashFlowsHandler::handleRequest
  access_key_id: AKIARVH33RUXXUS7VDOK
  secret_access_key:
    secure: FnkO9RplTfYVnO7ctcg1rwXFAOx7qZTgiV/MRvjbT5K00bLPApDbfZZhJnJgs+5Mk2CT8JTndKvigfQGXo2peUYwnGx4k4V4vpJCKlvRTHfAHs2Nf5v5LOopfZihIUGGl37SUnr85zclYNlnspV/O4MLPIGNMMSmBJnPSy8i1SyLSxHL/j006Uyfsjs1ihfwcfenuLAHY+lNntf/Fr8FBaD3jR0Q+f9NFYU18E11u1PDVN5mAK1FW/sKClURS/NBEIEn0HRtytqcjUlWI6AlT1CdpEy2X8Et0rY9beRQJNKy0/N8qUlV1fdmQPuygYW4C3Q+QkQj2IGL7t9SLhviQyKJugIa3lZH+Paf3FPk4Zaq2eMu+rjpswXg5Os/MVEfRwJT1uBQnxaS0KC9F9hKKLHgZKH7FVCGOnOBenZweclzuHq8ZJQvQ+z58oSfzuOM6AKJ0/e8OM8H21RbnDFPYtJrb8UxykmKuFEfOvUJXXmPtEuTyzuHj/0eAnZrvLWhbJPXKeb1uRuzRbHH493MFFoa1jfDEbSZy9t065jiDP/tr8lme9rWORbTYLlDLFbP529Nf6MyFZXKsHDo6z1RprIA63funv84AFig+fSiEH1GwU0tZTm35V8WJOMGHm4fPouf3yuH03HSHW8oha1Efcfyaim0436Q6Wfdb+oV2oc=
