language: java
jdk: openjdk11
deploy:
  provider: lambda
  function_name: getCashFlows
  region: us-east-1
  role: arn:aws:iam::114344824111:role/service-role/wucashflowLambda
  runtime: java11
  handler_name: com.wuxwesty.GetCashFlowsHandler::handleRequest
  access_key_id: AKIARVH33RUXXUS7VDOK
  secret_access_key:
    secure: 14CntCS9UlIhAuTwIxnzSrgKh1ZJn1/izfufAVgrFVLo/JX2s5SrJSM+9/ASIS7gwmvfgCP0H0/y2bbQhYu2/JOuq8STRZKgsInjnXQCvnlc9wiRY8s1OxIVpzNuMpvFOR9A/KSD8Tuq7dJc6nDQ5z+xpuVq9tcX3jDEQ9TKouK0UnY+4n1p2z3wNk/4FLiQKMc56Ub0WQOz9D7tBa8LhpiNy9s6OxqKOTOUvBEAvBLI6Ji3yjIR0uieDmHGIX8U35NOqJLepEzfO0K+ZRKpHHxT4yL6c7O1KlhkYtsWRMJOhVIs1WNi34cgD+v0pvIsPz6vTrjaPQazu5EcYt31voTOUbszX9272gNQX80aRfhwOl2shs5C8qXTh0dDm8K+oynNy7Sa7yMM63orMla3oijM1mxB0GGXmRyeg40UfUrRm7DqWgiyD/+sL2SRC8CxJ8RziclyZtlQUzvTFvY7wlg2b2/fDloCFermwl1SYZUVzgmN7vbRgsdpNGe1CPz1LTdRwQ8j/iap8eaOFfpTRsMOk6oN/W7w6bxrYDm8Hb+LJNGJ9fSXxWz0gK3ynuGxv5461auPDiVSZ5HKhsOGjBc6ouF4dCrGFSB82m8cyKFLGsVrJrWnIgT4bO+Sww3tNo7NhSWkR1Oe+ljDw57zwwoun4h3lcidY1DiluVbb84=
