language: java
jdk: openjdk11
deploy:
  provider: lambda
  function_name: getCashFlows
  region: us-east-1
  role: arn:aws:iam::114344824111:role/service-role/wucashflowLambda
  runtime: java11
  handler_name: com.wuxwesty.GetCashFlowsHandler::handleRequest
  access_key_id: AKIARVH33RUXXUS7VDOK
  secret_access_key: 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