language: java
jdk: openjdk11
deploy:
  provider: lambda
  function_name: getCashFlows
  region: us-east-1
  role: arn:aws:iam::114344824111:role/service-role/wucashflowLambda
  runtime: java11
  handler_name: com.wuxwesty.GetCashFlowsHandler::handleRequest
  access_key_id: AKIARVH33RUXXUS7VDOK
  secret_access_key:
    secure: ahHPwClie3E77V6yz3bldvFfo2n8Ab1MZBR5ZB5GJvc8t8y3M6i6h1BsCZ6WXz1FFI9uEvmNv5p699UTbiWwrcI+28CXLgbrtFSj/RbYvULO890BwjREVVt/FvlA8Oo6C+ADGTOE8bBAFmZZqXdk+2F2XqNuUwjuIdbDtW07M7bcgSXJsSLJ4g+eYy2I8F28T0nu1Nm+I7fo2bVnb9KVrxI0KD0ntMyPgtoXiUWpVsZENgUSKJapRwyhb4nRHls/dSEZoZ1Yfj23BteDvH8+DY8TmBopALN5ARHqCINrVfuShaWOFbFwOmx3lHMP5gDaBUn2+/GS/OrZNNNYe69MmHONE6tdnbjlFH+gXOekqT3pvQARSwGZq5RAIqNX/OQ9jj95lG8O/xpR3gkZ4k/docxEggMwLKzOA1iltwRIJHpLx6XHipZXDyIqs0EJnbJ5v+jCZmWbbdbWutwaHILCVV+AwtKtRqas/ypGtOy9rU2q0RiDuKZpl0giIMskr40Qv5ol3BmmNfUaXK9XNoXRuL0chZI1Kbco2Uw17luK0vXw8dNE2cBQwOfKj4qz9kIVOoRf/VCT8tuNezWoVfsJ3ZxbV0D12x00mfOrTGF6UezHinFIf7uQAsXks6KWs90R8C/TZI1rGOIO0UgV9cPLcYmFZTlnfaGJDsqTPz5XIYc=
