platform: linux

image_resource:
  type: docker-image
  source: 
    repository: openjdk
    tag: 11-jdk

inputs:
  - name: repo

outputs:
  - name: out

run:
  path: /bin/sh
  args: ["repo/ci/concourse/build.sh"]
