
resources:
  - name: CashFlowLambda
    type: git
    check_every: 10s
    source:
      uri: https://github.com/wuxwesty/CashFlowLambda.git
      branch: master

jobs:
- name: build
  public: true
  plan:
  - get: CashFlowLambda
    trigger: true
  - task: Build project
    file: CashFlowLambda/ci/concourse/build.yml
  - task: Deploy artifact
    file: CashFlowLambda/ci/concourse/deploy.yml
